apiVersion: v1
kind: Secret
metadata:
    name: odoo-secrets
    namespace: odoo
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:507I+A==,iv:D7wSOLsrr8i18DuXF5BlbDikff5rJBUYT2GAKhRY2Eg=,tag:EQMruaW4DgMjzv0v4uQeCw==,type:str]
    password: ENC[AES256_GCM,data:lI1WqS9ALOORbhNZVBnC,iv:3Co5QCyzHpBWk1UqidsKmDf5DTrBWZAbN69wCbQH9i8=,tag:VBgb9ZRgFOxrH6d1wi9VZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNy8zR3pjdk9HdE1mRnI0
            YnVVdzdXbEllT3ZsVkFOYWNiK3lOSXNoNVNJCjVIaENMbm1zL05EQnBLYy8yWm96
            REExRjVKN0VwdDhWZ2Judk9lVjFVVHMKLS0tIDNoYm1EOGNHWnlFN294SlNwSUpD
            N3k4SjNycUhoL2EyeUdFWWZmcU4vK3cK/eeWCM3JvhllotQanwcxH/OIynbVHrwg
            umkaMcH4HabFWIVsFgHlf/PaXVdupqKlQaUBsTHPjcPfqCqY0Ooqyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T19:47:20Z"
    mac: ENC[AES256_GCM,data:GONG1ANjR7eBQRgV0RUXeRtWbAor2DmXU+2UgeESzpFjAtc6iZ0qhU3Kl3yFa4wwB9tWDqdguNdR+Ix35YvGf/q/xGr4JifLnP7h1dXlr0Sc3a4xm/w3Xi0w1+nNd0nfDDduPAt7MAIk3l+ktbpwvj/qdyl83mUJMx29Sjg29JA=,iv:Bw4E2a1c2azdM8e5ODsDKUb7Erm+ZLhne5Oyf7G9tHs=,tag:hYPrR/USzkRQTsXrNMlhxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
