apiVersion: v1
kind: Secret
metadata:
    name: odoo-config
    namespace: odoo
type: Opaque
stringData:
    odoo.conf: ENC[AES256_GCM,data:yioLQRjvp90uCo8FoASr+uEwthMRM381wFFLSLxNowjESufDyrWP9P1lQnSui16MsA8lNHNByInOek/nvHfE//dq2H0h4JF1L0DCKF3KBAPt5AsVDlsQSUjEcp8UHccQZiXtx5y+lYpZo1GcFaNQnH8aS4O0W3sJybcVuO2/BS6EcNA/scmhZLs4XxxMuzkj3egh8KRv64xtHNxdFcSk7QkS+lPDgzTLJRW9NXL1pRimLu6JegghNit6+2Xp+z5YmyVtbS+HOw2feCNvr5kVkMqhbBgEoobK/s65Ozpvunb6lX3/J5Pd4Lc5jHet8OsUXVjd9w==,iv:VNiQkBCJdUgm/GSI6eIN/5xAVRB8Fq3FQ3dh+fDli7c=,tag:0nHcj+28L2+wBCzZMc+oWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmejhObUlhK0lSY1owcVY4
            OEFrL3o1V0pLbVUySGF4NUNib0F2WGVKOVNrCkdhTkpLV0U3YURDbmY4eUR2M21k
            d2R0anFPMXJMQjNMYXp6cWhRMW9nejgKLS0tIDA1LzRPWTd5Z0V0UEkzNzNFeXA3
            TVZQaHdrUUNVRS91WlAzcWYwY0l3blEKaTr5GGChiVqGme+12QIULGfFyHravEEx
            g67wCBv9CimNmQACN28r5Rfv9mKCWcfHlsvWJt+77bNgKAP9MUxguA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T20:19:24Z"
    mac: ENC[AES256_GCM,data:3NWZ/3K4fhqtiwkuchFwJsEIc+T4t1urWV6LR6Es95FbXItXej3zv8IEU/CYAkWx/i6mp5JeuqGAs/P6jsawoZ0l+nffqFTL8XvyofmhgkV6VGDSmrqdqzNTqD+ztxSMTsOpWwaRL2HiAbq+xG8/3qCBlkUnXuqS5VZUQnrrhSg=,iv:Ra68EyMFIpG584QyIA2BSSAAyQbyHDZJkJQJ4fUJiLw=,tag:kBV3DDFT0x3PHPECzctvww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
