apiVersion: v1
kind: Secret
metadata:
    name: odoo-config
    namespace: odoo
type: Opaque
stringData:
    odoo.conf: ENC[AES256_GCM,data:+pDQFYXcUIj+8UY7Y6Sk1GinUQKMjVFVctUcrWWui8RBnB8cSRaTQr6ZDdDv9KYsBKR7m0UwKKl17c2KASqyCFSFY1CfInXlctM1eI0Hq09SCJuVVbzx3QDdTCwXaslKVJh6MxOx2bUKzF0ZKrUpyici0TCmClwDF7a0gUVjiG1ddj/pGr7sENg4eSQ9SiPy0z602xa3ciRtIfpdfvu6n3ub7rDjj6sWZL9RjQq1awzfO4aAPyPPiIF9A3sUIN1o4wnk237X1fKXIPAN7AtonG6Mv8sigpvNsGFYKjFCXs4CGe2tgYkgTiDw/PBNRy4K793R,iv:ra3e/av+BYi6vq96FYBxghuFfjhAvqpb1zPSEYpPZic=,tag:94q3A4ScfvRZIVSTF/NmrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmejhObUlhK0lSY1owcVY4
            OEFrL3o1V0pLbVUySGF4NUNib0F2WGVKOVNrCkdhTkpLV0U3YURDbmY4eUR2M21k
            d2R0anFPMXJMQjNMYXp6cWhRMW9nejgKLS0tIDA1LzRPWTd5Z0V0UEkzNzNFeXA3
            TVZQaHdrUUNVRS91WlAzcWYwY0l3blEKaTr5GGChiVqGme+12QIULGfFyHravEEx
            g67wCBv9CimNmQACN28r5Rfv9mKCWcfHlsvWJt+77bNgKAP9MUxguA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T12:00:38Z"
    mac: ENC[AES256_GCM,data:LE3Ptb2etEW2Om0Z80JCD645BtOe2jP9+HifUSx58BULl1rzrHU0I+qedBWD9wulr02is+GE4nu8WkLOmE7iAv3k/0h20KkjORmGxQqYZIl3ukTooBtKS2HsCJPhJnmj+Efanw1pFTmUBR0Qha3SxX6QobtwGww3VRdjcGS1Iiw=,iv:/U18NwHL3JP292E/9PuM197csv3yOcyB4myxFxl6LZo=,tag:6Kt5vGHRIsWCC6m0lZYizA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
