---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: open-wearables
spec:
  instances: 1
  storage:
    storageClass: longhorn
    size: 50Gi
  bootstrap:
    initdb:
      database: open-wearables
      owner: open-wearables
      secret:
        name: postgres-auth