---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postgres-ingress
  namespace: open-wearables
spec:
  ingressClassName: nginx
  rules:
    - host: postgres.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postgres-release
                port:
                  number: 80