apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: open-wearables
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ZqzS8/a3DFnsdViWIcg=,iv:dlxWAiveYthUV6NN+iHf2sgjl+J8kYHgzxUuhxejEf4=,tag:7stzUNtIDL8oBCd+PXQI+A==,type:str]
    password: ENC[AES256_GCM,data:moG9oSU3gODuanTs/m0=,iv:CFUUBn01Dn/e/mi0eeBzcDyhE9aN4iSLsGhAxMRxoF8=,tag:4i7UF7ifb2YedFYxdj57rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNklLSFAzbkxYK3NEMkpC
            WFFEZW9HS1h4UFhYWHBuQ2srOVJBaFVGcWo4CnFvSzRVZ09WNWNuT0Y0STNUMTFL
            VTRUS3ZmSXhqSmFWQ1lBYkVtZmNGeW8KLS0tIEN6aU5iblVKTGNaVnhIVHFKdk1V
            L1lWTGJWellPZTgzREw3UHhJNXNEU0UKmhnvfY2JU2etxAQkqXUq/g2ePa6RKwzu
            6F9x3Fq8fqsIWgPY8YeWrp/9IGKWfKnCNSoIV3n0sEJmblA9Wbs4XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T12:30:31Z"
    mac: ENC[AES256_GCM,data:wVpos+tsYbpqP3wVRvM0XTlP6HAHmraukBcail+hWipWBrUMKvDM27MZqzvt3807KBDEH8v5nKaZBFPOLv1aHFR54uBqDlk5Zw1KpoiOYCtDuMw7W+SEzzv/U75kqes/XLUI9O15fIpGF2xDBD5wSNFLQiwGNzqwLaWwpp5CyFM=,iv:NhdWqPRV6gdbwg8u0FPl/T9iB7qAuKkybvdU0FEEgGI=,tag:/Ob8tlqBZ7Kyxmx6XTJ5fQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
