---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: open-wearables
type: Opaque
stringData:
    postgres-database: ENC[AES256_GCM,data:sRMkOdatD6uODAoUbiw=,iv:DvXWz/hM9V7PCjLb3an9Wuj/eYCYeQiFiSV+S90ntGQ=,tag:jgEVX0K+FPFDy0WZu73++w==,type:str]
    postgres-user: ENC[AES256_GCM,data:MpEmK8j6w7bbZc/etSc=,iv:QmkcGYXzi4kT8n+Zv2iq9DHviyzILexEMwQ4pIFIhM4=,tag:phQT9L2NoMmobAu06BJi2w==,type:str]
    postgres-password: ENC[AES256_GCM,data:jC08j+vSPVNBHvF7iCw=,iv:yyvq/ooCX5J/uU30yHo+HqmFnxGwWtnWSvDlfiuTuT8=,tag:A9ruJ/T+m/KGBZMdCamDfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNklLSFAzbkxYK3NEMkpC
            WFFEZW9HS1h4UFhYWHBuQ2srOVJBaFVGcWo4CnFvSzRVZ09WNWNuT0Y0STNUMTFL
            VTRUS3ZmSXhqSmFWQ1lBYkVtZmNGeW8KLS0tIEN6aU5iblVKTGNaVnhIVHFKdk1V
            L1lWTGJWellPZTgzREw3UHhJNXNEU0UKmhnvfY2JU2etxAQkqXUq/g2ePa6RKwzu
            6F9x3Fq8fqsIWgPY8YeWrp/9IGKWfKnCNSoIV3n0sEJmblA9Wbs4XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T10:13:33Z"
    mac: ENC[AES256_GCM,data:wfi5Y8D/Kc7t7JxSFEf2dFDNaO0HvjWEziknUu+E7mu8Z80xkjMYVSMzToX9TUgcGIZ8iYBkn36t4X1YfNbR3CXRfZ2oE8FSrhN6sXoIXkDxAxVjOp9dayhWoj8RMv6xTo2/KRvTWwrX5jGosQjr7lDY5k6AxD1EkP+XNHA2muM=,iv:ywYpG4RVusg02BqT3U6wrl/lRBRUKnt3hNqCQaQnH9A=,tag:m/+n1Bmps6pGZV8p7FrG2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
