apiVersion: v1
kind: Secret
metadata:
    name: github-runner-pat
    namespace: github-runners
type: Opaque
stringData:
    ACCESS_TOKEN: ENC[AES256_GCM,data:+sIwIiHEI3FrqF13z0nSAdx+F/sB+4/upK1QVgbJX9RQq5sXok6j/w==,iv:6ddXMSjUq+3Xuf4cDp6NE4t8XDdVMt3tsHzzG63ugM8=,tag:FSI6j5sEUnSZBibXlrgBxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TUxtdGVOdkRTd0xqdy93
            ZUkvVlI2ZlU0bnZDUU5NanpISUE5Wit4VVZVCjFKT0VpZ0t2N1JWL1Vrd21Yd1pL
            L2Y5ejIyLzNDUXNueWRVTEk1Z0tzdE0KLS0tIHpzRFlGMVY4UENXYUt0NUVwVy9M
            Q25YaGlzQTAzblUydURKL2NIODlPTXMKbg/y4zy7tjj0swTGQhUV6YR+YMIkHpQi
            8hYgv5Bwawoidii/D0RBgccxuwU6bVVLBh+i7dFjf/ZDqkxWANC0kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T12:45:07Z"
    mac: ENC[AES256_GCM,data:CfXyvu7Vltqr4KPh5JhQliAMf6F7EqsEIEZKoSiJYZvDwIcSBvdutQjK5Lojzf4xSLLnxmtdWUSMVgBbmvd/4DIUkA3R5GnVyja9wU5oCVOYGlgcxuIrKSHeJ0EORDOmSswlafp6yaWdPzbpDNla2sQ9HhBbsyfsJqnp5D1nkUU=,iv:x4OnhNS9RB05kc46RmbNV6VKqkmvS1KTrSd/P/9N9Q4=,tag:Q3S+wHbOdM28BjY9YSQ/BA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
