apiVersion: v1
kind: Secret
metadata:
    name: image-generation-pipeline-secrets
    namespace: image-generation-pipeline
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:l9weYVbP7w==,iv:MT2gvszCdRmfG5NOuFiaSEr20G+GpXVznT23d2zuCr4=,tag:nWbYS/qI6P8U9l19ojIsbA==,type:str]
    password: ENC[AES256_GCM,data:808hvoh+LS1MPZblxUtRxfJD2pts7w==,iv:wiYK1Zl1JHu0AlM+DAdaroP0s4E3EiBC4bzzMkDvdyk=,tag:OATprY2RhoQod6ZqwvTg/g==,type:str]
    connection-string: ENC[AES256_GCM,data:3aIa+9yWojMCi1IBCLPObx0J8VG/TSRwFaRlmYqfKLRGoT7y6v/jnc5zdFf+38V37uIsITIEHLJ/RI/gGEcbwr0oWdlGgmYxB/WKcOk468gv1JSCOb81bwRg4/I16m70rRDFieK/ExxZP219VPJP+9lDjCkcRzVr5gLb4qVcZks=,iv:6m8/TQla9msyyszN3CMCnaPeV6zQUx7y+B4iJpoNrNg=,tag:oh6aCqjtvgpfmd9IjDNvzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Y0piS0Ric0RPTTExVytu
            dWpQeUYrZjZSQy9pZjh1ZWx5eG5oa3VLQWlJCklrTzFvNmhQWVlaTXZJNERiMXEw
            WWFzQlB2eE85eUJ4RWN5MlRSK2RDRTgKLS0tIE8wVTdWdXlJY1ZoUlFlVzJIeXlO
            SFpnaXZzUHF4aUhFTnJEdEt5NlR4MGsK4LcHHMU2ydpGXIbmZMDXeu8tSqLPX2Jn
            wBKG90POMFkUBxsPost3hVUKN2EbdrzsZZcyD9hBompwat3lVNnmqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T18:24:49Z"
    mac: ENC[AES256_GCM,data:J+DJuu8j6XcpAS8hGrncF91ZO8SAGnSoqDrqu+EoRzUyqYhujiB+fJPeqNwJWLltGL/VIIRDxtzc+Z09ZWKT0SZzfRlNOOLK7clyDAOs+iv07KG9j/7yXIheCB/D1yGJSeCt3J7yl9pdJ0L4orp9o9xKsu22V0xEpOOb/6lm+yo=,iv:ZP726bCYNfv6ddIUj94cSQECFm0KQImAMsLU4L3lZZk=,tag:15EhD7qZLK03JmJFRZPoww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
