apiVersion: v1
kind: Secret
metadata:
    name: image-generation-pipeline-secrets
    namespace: image-generation-pipeline
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:G+uGJ46U2w==,iv:bnIDJbGmr2ip5myMuQjOhkIk3fOWF/dR+gO1kwB+MPY=,tag:wtqH2Z+Ci/JOPElZv2thUA==,type:str]
    password: ENC[AES256_GCM,data:a9p/NyO4VxQiWd9DP/mHJn74Mog32Q==,iv:PF0iYcBbHHItg2cqbBMHpp9lAheCxSnKdXlaonqRsQg=,tag:nqGoqjVzvCV3MXkeSfWFfw==,type:str]
    connection-string: ENC[AES256_GCM,data:BiGBF2VmWsxI7J7/8wqti+xS1zkm0/dvcA49gcwW4CN9PE1M43Bgn7DoCNUvnlYFDAwIQdU7FADbKArUjiEuTgKl4fQTnn5qlt37UZ7s1mHcduGvKkJ0YwojyuuMiSbx49JiXlkUwmQFPVQxtAFuY97daxFj/LnvmYTsYRcR51c=,iv:mJLecbwOMIKcM7+GRTsLP6EEUcV6cScEg/rYOc8RnRE=,tag:3fRPUHoZaTc7hzU4M9Bw7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VlNIMmI1ZWdhL3hkdUQv
            VW93YzJkUFFpQXdBNUpQRXhwMWtFZXkyTkdJCmhNYWw3T1IvZ1RzZ09MdEZOdXQ4
            ZXNKWU4wdGE4YnptdmlvMzJpSnh0bzAKLS0tIHpyRmVtSFIzaVBQWjdSbHZxQ0Qz
            MzVzaE1QWTVkMVh2dVJsNkpjbHc3NlEKAJ/IROatEMdapd232zIu/QhibS+PjmCE
            Mwv7iEEzwGgWZ819U6+QpgFUX/mTvrcsEB/F86przWHpKLPVzb5FuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T15:56:11Z"
    mac: ENC[AES256_GCM,data:jsU4GmmSE1hPqka5yNL3SthltICynMQKHLsexBb24NWyW3qFHibBDdx0rim+o8AmrnKhfBQ4mrNOHE/Ua3kucIqbxpbQfc6VGjCT+IkueDMeNDaEdV9xW7p1McQd/iacRybO9vQJGJuD/Qn90WosZjsmeH2yk3ziptsZgv0EU34=,iv:/DBmWyWKuZdNtYlFdlULY/Nh1qSHveJIUKQWi67rROA=,tag:FDaaT0ohqtBXV0iJleih/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:gjOFl0Vi0EOO5j4nF4eH/sDPu/QDnxrNL7NvRpyhwEeL5EQtDOakWVsZfwa9Sg31iDchT/u1jsjEoVXDmfA2AINBAJkjZKqR3hK9aZ3yvZ7Cv7EIT0/pQGBrN5/z4aYebmhFZshP6q3nM8D4cbQ8p+zrB+ZVzFTsxUKwX28UeOo949pSlbMvJLGN5LwRlhvKju4geZADqDJKoF2iP/SF3gkA5b3n5JwmTooqF/nyzizFcx7SCFT8UBvaHB8meDJC9PT/OHNrqIOz93UUAFxnc04PmddrZnZA1od3tg2UfGUsUiecgnN4jH2ijram6SS2DaInsUnWUWA=,iv:H+NC8kEwLc5/QJBXmfsoIkcKYLdcD/8KYKxkN/QvHd4=,tag:TXqDP4HUFJ3/wM0IAexFDA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-pull-secret
    namespace: image-generation-pipeline
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VlNIMmI1ZWdhL3hkdUQv
            VW93YzJkUFFpQXdBNUpQRXhwMWtFZXkyTkdJCmhNYWw3T1IvZ1RzZ09MdEZOdXQ4
            ZXNKWU4wdGE4YnptdmlvMzJpSnh0bzAKLS0tIHpyRmVtSFIzaVBQWjdSbHZxQ0Qz
            MzVzaE1QWTVkMVh2dVJsNkpjbHc3NlEKAJ/IROatEMdapd232zIu/QhibS+PjmCE
            Mwv7iEEzwGgWZ819U6+QpgFUX/mTvrcsEB/F86przWHpKLPVzb5FuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T15:56:11Z"
    mac: ENC[AES256_GCM,data:jsU4GmmSE1hPqka5yNL3SthltICynMQKHLsexBb24NWyW3qFHibBDdx0rim+o8AmrnKhfBQ4mrNOHE/Ua3kucIqbxpbQfc6VGjCT+IkueDMeNDaEdV9xW7p1McQd/iacRybO9vQJGJuD/Qn90WosZjsmeH2yk3ziptsZgv0EU34=,iv:/DBmWyWKuZdNtYlFdlULY/Nh1qSHveJIUKQWi67rROA=,tag:FDaaT0ohqtBXV0iJleih/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
