apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: localizer
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4kUCqQtWs7C+MNo=,iv:QmcKNEvSVADVAWYM+ylMs6M6jN6DsaG4UG9T7sWqPZg=,tag:OjCENgDwh8m+r2LMgcXu0Q==,type:str]
    password: ENC[AES256_GCM,data:tfIPNnO0r7C4yvXiXYSUiSaxGYas+PNLz3A=,iv:q3cWjLy24EMglH0d9KEm8RdA8zawYctomQh1sIRD8MM=,tag:UfYoMPhGtKm0/mpIApaXig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUFY2NzFxTE1nMTVXS1BT
            YzFKT0R5QmtWZWlLRzlCcGVqaDRYVlhoRkVzClhORnFZZkNHckRyaEgzSG5nQklI
            NjEzK21aYndpekFMZ2ZkUVl2ZHozK1EKLS0tIDFCcExkMmVwUGYxcUFxOUc3K0Z4
            K0EzNXphakpkSmxkMy9VNjdSeEpKdGcKQj9QGaI5vdp72oEkZt5kW3E0ZLVkCcVt
            heVW666rsL4HzphKcXLjkEP+lN6LW0l8Sl8nfLb1uWLlZhw4auAuBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T20:38:29Z"
    mac: ENC[AES256_GCM,data:y+ykYqNdjKGfSt6vJ9xFC1evtnez3FZnrecmKowlhGYZ9X8yA0671d+dHq7PrDSDVNbV1Fyzogccm8/yuQqskqMlsNp/cm0XgTVVY2RxRdvnWzfCTPFBF2HP3YVSEc1c3h7XnXxZuZcmqEvNoBU8p55N0jEw9ABHlHwF1U4HhTA=,iv:VtcWZItP+89ifj6LFwYYZcUeQ+K0saHsVT2Cn/ZDcrA=,tag:rUr/m24yNmthA/ZZ2L+fZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
