---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svix
  namespace: open-wearables
spec:
  selector:
    matchLabels:
      app: svix-service
  replicas: 1
  minReadySeconds: 3
  template:
    metadata:
      labels:
        app: svix-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: svix
          image: svix/svix-server:v1
          ports:
            - containerPort: 8071
              name: svix
          env:
            - name: SVIX_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: svix-secret
                  key: db-dsn
            - name: SVIX_QUEUE_TYPE
              value: "redis"
            - name: SVIX_REDIS_DSN
              value: "redis://redis-service.open-wearables.svc.cluster.local:6379/1"
            - name: SVIX_CACHE_TYPE
              value: "redis"
            - name: SVIX_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: svix-secret
                  key: jwt-secret
