apiVersion: v1
kind: Secret
metadata:
    name: svix-secret
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:jYWdoF7Mt1MCIfnnfEqDXD2PqSR0eotVW4efpRwd33m/D+nV7IVa4ZEHmTbJg8RxZDgCHCNUIFk5iC0AuL5cRg==,iv:QP4hOx7NjQO6l1Lfv5yU5rBPmDS9ggsbp2fPPEAKhIY=,tag:mXHDc6E5m3YwrsmKYUdHzQ==,type:str]
    db-dsn: ENC[AES256_GCM,data:Q7GN+dxs/k3JNfXSGaJpHiS/RIOKBBZxxhtN6oE+J0prjcku131Vi+y0CeqHKoTAHJK73Es63eeDPP11QNMiyrR65XgEgk5VPFhuZOqlAA9IWrzFtIIB3HKa6bAGW3cJl9GJVPqVsTqC,iv:SK5z74CRHWDNFsSeVa9kjCUovRTPxGtOq482v5OK8Gk=,tag:mzNZjq1r7kXSfuDjGSNkBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNE1JRjYxcS9uYjR0WjVp
            MGFFa3FRTW5uZmRlRG56blhYTDVSUysvdjNvCnNzVFBXTDdSTHVZWnhqTk45SDgy
            cGlmRy9LZk5IMStWdUI4QWVrVWFIbjQKLS0tIGxlS0xYTkE4YXJWclZJUXU2am02
            Um9jNDE4ajdGZXVjanBwWWxHVXNBdjAKYBlUSiucmSDBJMQ/pUDkyztZDTwkJKws
            XGVVt/SXnYdwY+YLFLYnmlGjkJ7HYij8f+hIlZFLTdTtKvpZrlrWvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T19:00:10Z"
    mac: ENC[AES256_GCM,data:9zIQYB041oti0/YYqfDkgWu5Nw3VSa/USDU/4KdfrRKv0+D3oHCmDPu3vvjdWyJh/tPpTRZkbMg43z9UoNqRaLBARnRnD8Krcojdh0RXUOI5dssPA5vmoF084fh3GmdmBg4m31lfhd4NkbBo4sOdBAiUDBFabox8zer/ocTEYf4=,iv:AMlnDh3Yl5vRHB+HktOQrSIsFwlX6fk2OeInnDyRrrA=,tag:/44r29PE1zm1gJfXJsKqjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
