apiVersion: v1
kind: Secret
metadata:
    name: svix-secret
    namespace: open-wearables
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:jYWdoF7Mt1MCIfnnfEqDXD2PqSR0eotVW4efpRwd33m/D+nV7IVa4ZEHmTbJg8RxZDgCHCNUIFk5iC0AuL5cRg==,iv:QP4hOx7NjQO6l1Lfv5yU5rBPmDS9ggsbp2fPPEAKhIY=,tag:mXHDc6E5m3YwrsmKYUdHzQ==,type:str]
    db-dsn: ENC[AES256_GCM,data:Q7GN+dxs/k3JNfXSGaJpHiS/RIOKBBZxxhtN6oE+J0prjcku131Vi+y0CeqHKoTAHJK73Es63eeDPP11QNMiyrR65XgEgk5VPFhuZOqlAA9IWrzFtIIB3HKa6bAGW3cJl9GJVPqVsTqC,iv:SK5z74CRHWDNFsSeVa9kjCUovRTPxGtOq482v5OK8Gk=,tag:mzNZjq1r7kXSfuDjGSNkBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNE1JRjYxcS9uYjR0WjVp
            MGFFa3FRTW5uZmRlRG56blhYTDVSUysvdjNvCnNzVFBXTDdSTHVZWnhqTk45SDgy
            cGlmRy9LZk5IMStWdUI4QWVrVWFIbjQKLS0tIGxlS0xYTkE4YXJWclZJUXU2am02
            Um9jNDE4ajdGZXVjanBwWWxHVXNBdjAKYBlUSiucmSDBJMQ/pUDkyztZDTwkJKws
            XGVVt/SXnYdwY+YLFLYnmlGjkJ7HYij8f+hIlZFLTdTtKvpZrlrWvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T19:09:06Z"
    mac: ENC[AES256_GCM,data:FoTapD2IIIFDbQqxvyla/Oj/Fvc+nmPWx1Bim0JmYlrLnIVc6oZOzMmy01VZQH5XDMt0abQKhX+ujFfUHyf+zuyVUk6N1x1+Pn8ROrrpE5rivuw43gdDPQhTNJnNxkfimjApBasMvIgWfCNL3ObgiTWPywQig+8csLwLbG5E0Ro=,iv:2cvfK+Q1OOeii4DDlutbiM/p2AEXbAieaGneHW8Zl3g=,tag:K0Hcr0LjfkacafPZmsp6hA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
