apiVersion: v1
kind: Secret
metadata:
    name: svix-secret
    namespace: open-wearables
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:jYWdoF7Mt1MCIfnnfEqDXD2PqSR0eotVW4efpRwd33m/D+nV7IVa4ZEHmTbJg8RxZDgCHCNUIFk5iC0AuL5cRg==,iv:QP4hOx7NjQO6l1Lfv5yU5rBPmDS9ggsbp2fPPEAKhIY=,tag:mXHDc6E5m3YwrsmKYUdHzQ==,type:str]
    db-dsn: ENC[AES256_GCM,data:Ziz5V+4dA8FReSF8nYYtTDjFJjxzylPCILa0wwuhWyQ2opkrbRzavd/ZMrNVgT3hR44Fi2O247fKpo5n8jDfWxbWHmiFZFuQ+9cT8WXpjgqlRAJ9iWc2R7VWsPj/daewA5PMBFPTNQfe,iv:qJ4UjysOKwzAoOGRU5IBuQqN7BEPFpnVPqvCsme4zM0=,tag:p8rKYuSJltCkPKPeYtl6BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNE1JRjYxcS9uYjR0WjVp
            MGFFa3FRTW5uZmRlRG56blhYTDVSUysvdjNvCnNzVFBXTDdSTHVZWnhqTk45SDgy
            cGlmRy9LZk5IMStWdUI4QWVrVWFIbjQKLS0tIGxlS0xYTkE4YXJWclZJUXU2am02
            Um9jNDE4ajdGZXVjanBwWWxHVXNBdjAKYBlUSiucmSDBJMQ/pUDkyztZDTwkJKws
            XGVVt/SXnYdwY+YLFLYnmlGjkJ7HYij8f+hIlZFLTdTtKvpZrlrWvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T21:09:41Z"
    mac: ENC[AES256_GCM,data:pNqilLsg9kHKpc6zFQ9jDgEGkKSQHci/VIB+9Dgb459SE/CKaUK3B7+IZO3yMMRVl+yaVu7vaoB23jqS53VMQkqX0svqN2PM1mSxDghAUZdK6JnV/r5zoasD/X3kq4y7/5vCNsXdQBBAgKTbEI8EmokADcwqcSo/eYILBp4x6SY=,iv:/cexFOKUIfujm4Z0tvj+tdnV+NvjbZdjdVXKPZ4B+MY=,tag:N/eiklGxIhuyxpwV64R7kA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
