---
apiVersion: v1
kind: Service
metadata:
  name: svix-service
  namespace: open-wearables
spec:
  selector:
    app: svix-service
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
  type: ClusterIP