apiVersion: v1
kind: Secret
metadata:
    name: agent-secret
    namespace: ai-agent
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:gJIqKJYR,iv:gezCYN/xGWhueTTDT5tv7k5CTMCJW+M1jJAc4xr/JGE=,tag:I3olUip7Qkn5HKD79JQHBA==,type:str]
    OPENAI_API_URL: ENC[AES256_GCM,data:5/O0MMZzyrqK9c3UEby6O/HGWgZyrhw/7oghneaxEw==,iv:cHaVzXT5tochO2M50d7Wq3YGHn6p42wBF0k+fZHjUyY=,tag:wS1QfECu53z0sSD5R5bsEw==,type:str]
    MODEL: ENC[AES256_GCM,data:Tuaj1IEq0E2zm+Q=,iv:FzZmn8evHaFsBUEAAAFHgcUjmY0hx99VMCwN8IrqPfg=,tag:BnHGixr+L8e8EvsbHaymhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSXhyUnY3NFV6eWNKam5I
            T2hmS2R1ZlJPcitiZUNVa3d6RVZ3SmxpWVRBCnhqQytoVTU2cnJBVUx4ZHpTZThO
            WklZbUtvRFZqa1Q2S3ZRZkJEd215ZVkKLS0tIDNLTDdmbXoxZUJKeksxQ3FlRUI2
            ZDNxaFovajJPMDV3ZUlrUWRVMzNqbWcK80j6H7IlM2rQE/SKZQucy7ICIAFKLVaZ
            5qV/yHSPxMue4xAV1/1NLWEa6PUHe1plFL286K6EsNmemuheI+VAPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T21:21:27Z"
    mac: ENC[AES256_GCM,data:6IlQcqROHTXFoCh0IzI/odGy8b9rsbTwDIkEXCruAglpxD80X/KF77zJujFhe5JezFsJaGnEM7FKevjT9d6LG1ZP7OjqH2zez3GOZOh8Jtw1sktt/bgpISTFAc3lV7q5sJA2VKbaLLxLxT79kMB2aQWCI80ABqnlfmEIHA9YXwU=,iv:84iqYxxVpVOzhRP0sb2Xxb2QxvCTncQIgzcVfWPSfhk=,tag:Elj+C8243ZPiC+EYkXAlJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
