---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prefect-ingress
  namespace: image-generation-pipeline
spec:
  ingressClassName: nginx
  rules:
    - host: prefect.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prefect-server
                port:
                  number: 4200
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prefect-tailscale-ingress
  namespace: image-generation-pipeline
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: hpprodesk02.tail26593d.ts.net
      http:
        paths:
          - path: /prefect(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: prefect-server
                port:
                  number: 4200