apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: image-generation-pipeline
spec:
  instances: 1
  storage:
    storageClass: longhorn
    size: 10Gi
  bootstrap:
    initdb:
      database: prefect
      owner: prefect
      secret:
        name: image-generation-pipeline-secrets