---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qdrant-ingress
  namespace: qdrant
spec:
  ingressClassName: nginx
  rules:
    - host: qdrant.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qdrant-release
                port:
                  number: 6333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qdrant-tailscale-ingress
  namespace: qdrant
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: hpprodesk02.tail26593d.ts.net
      http:
        paths:
          - path: /qdrant(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: qdrant-release
                port:
                  number: 6333
