apiVersion: v1
kind: Secret
metadata:
    name: qdrant-api-key
    namespace: qdrant
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:G/USIjy5W4cEHbbRxLXHOpn90u026hhVxhuX3TwM0vq2wjA/mtMIx5GLqqRJS3WYcpOoO2Xjhj0cJ8dWVUvskg==,iv:VjocWrcMMHuNB8PQ8UTrY8K5iz4E1oU5dD/Qh/miiPw=,tag:uW6yQAMJmmkjcjZvKo200Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVm5Vc3UxdEw0K2NmQ2dz
            akttMEVlVjhPY2YvTGRtOE9RenJwUWlQTkRVCjZ4TFlITFY2MkUwYUNzdHFrcXBX
            VmVWMUFvRVdnam1mVHFPUmd2ZVFvZkkKLS0tIEJ2ZThkUUFtbUN6bFVMS2ZCK084
            SkFxM2pKYjdwNzdKWTY3SWp5OE4wRUkKB1bnsuDPidR6OYuSut6gX98HVYmjawjR
            hBmDBxj/N+1tvHeOZ0u289eag/fJ7+MpFqIgy7mZLpcK2UwuQME8qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T08:39:13Z"
    mac: ENC[AES256_GCM,data:wEZJY7osyVTZ/eOXDJY9brmIbJQccjrYFxYtje5P4MJU1Ek54FglOzEO3tuGlXwUdTxRgMoGFXXFAZimDjaAqBDiUNn5M0Cw3RWnIv5FL1YhrGCdqe0U8p54HaLcfCY4OsR8HbBu7VDSHV9FoyNL8K+my5khhI6rq8oz7q6a5G8=,iv:bD9rmLYZwQAotCKZaZnoUO/5XIKW+4JSSIpaCd9eS7M=,tag:4DTHPp+tSM9NUdCrpOWIbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
