apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: cloudflared-system
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:voAyfzlCAw0whakVKweBDL9nSJQ5t10uo95pikUe8UoYyTn5NX4Z9S3bULt2JIgDXeYBqL8E8HzZHE23sTellghFcStHZAemUjPKtLswVBweJbfSW74Zklgy4ujIJyH8PXtSL33OJ7sRvopgQjS1wuhlEMvlQqN2MFawmHM2zjF5AWa2AyotkveTx3qq1eqBwaxqAhRBI54KD9gKcV2R+nyr8dtWiPPPLJ/A9V1l2815ZAMsyhXW1aj6KFIYbQ1GhDM0N4CpcHShVIrVS8KSgCW8/FiLgE/26Uu7AlCRWklVGklvKh4l/hBT0qMCi7M8jbFv/7PkM9w=,iv:tUOVFT5iPxq24dtBwczV6g7BrIK720BlDeC7WulRGQ4=,tag:3CrThxyyVn1QKtzfdjaTdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSDVxd0RTV2Q4UzRpZXZj
            NGs3MFZlcXUvZ1Arb1VxbjZrYmdsZ0R6NVc0Ck9CMUpDY1N1M3RpcjN0dEQ5aTE0
            YXdqbFRDYlFVNzFoSVZKUUFzT0lWTUUKLS0tIENVQ09ZOFNrWEFVUkpnaDllRkt3
            ZGJJbFg2NGpGMGd3eUhpK2dyN2lyOW8KLttKSFqxXy1KaZtnhTGqtC5I/olNRAs2
            ArqNHc1Gm81hS5/QfbBH+gW4f23ExDDJOb7s5m/IO8O2dYDDpVH/Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T19:36:26Z"
    mac: ENC[AES256_GCM,data:I0O9STqsUMWEvtZUlv31WTOQyLMkMDH3EZT3TrYg1l0M3+PRgiLPMgHjjgLkDLzPWOG7gE0bRcr3LR/eJkSgPoOb9Ub56/5Qpfp+Kh8qnmlkYJlauN2FKGEKdR1Z6suF1OdC4zlY87Hz8EvlgUhVqzBp1RN3RbEBiEjst7vUcP0=,iv:oiuBOJpUN94dyV+pPooRWBV9n38j9nhTutRltKVl21M=,tag:fuT89iu3QAkIxndcTUzdyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
