apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: cloudflared-system
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:L8ibPYatPVBr37e8vz/9ibW6WdaskDqz1S9h/78lZuCTd9w014Vqa7NpPAjqQusv98k82+AUZye7BvwYIwguObX0AhjspVoYNG4IPVEmMk1IN7kbqqv3cljWDNe8DBThhkAsAp+KraLXp69l/BL6rpG6YPQNfQrB0vyk/gnRTtdqnUYCwaUV4V0jNoSfS8vBUROMAt4nIAo2ojPnC7kqXlSvfHGkyAicxJa9eFBMfxX//9VjrCUuHz72BnZcO2NHChvY/rpspSIu9IC0iFieG7Fiyb5A5wtPC77azNeMyoO6WqWuGHhvs3HjOv+l0s4tAe7BrrXaeMRzAxIsi1rhaKEL6Ueit1tT3XzaaiMy0BfEzgaRlHJnPWlx9bXLToOYatrAJB4+hSuYXAxmB6Q0baoUhVIn97DbKF2dgujlhVPashZt,iv:tXqAgD/sm9IeL7VCG18pKChNWYGOulE0W3MI2x21SnA=,tag:uqgGVds1JoxoaNezAveLkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSDVxd0RTV2Q4UzRpZXZj
            NGs3MFZlcXUvZ1Arb1VxbjZrYmdsZ0R6NVc0Ck9CMUpDY1N1M3RpcjN0dEQ5aTE0
            YXdqbFRDYlFVNzFoSVZKUUFzT0lWTUUKLS0tIENVQ09ZOFNrWEFVUkpnaDllRkt3
            ZGJJbFg2NGpGMGd3eUhpK2dyN2lyOW8KLttKSFqxXy1KaZtnhTGqtC5I/olNRAs2
            ArqNHc1Gm81hS5/QfbBH+gW4f23ExDDJOb7s5m/IO8O2dYDDpVH/Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T19:30:35Z"
    mac: ENC[AES256_GCM,data:xExub/4NDEWu9vkHQwWY/moJwiLWSl1IafIy8M4sO5sD7cFYOQr4cwM4xpi9LvrXAoTWV9HUgqrf/zf7EBtg8YbDLClpOS4PeowSbGmEBHBcx9L9yqBhObvKjPU02axaAL2MIHSD4Y0ByTSjeQ72YcsqrnwMDFIoJSuPlXRn1/8=,iv:a20Cp5Qnpoq6JSvH5haz5IRasv0COJSiKEWJ5ggr6d4=,tag:pECO48qwCK9EhOh7uwPC4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
