apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: cloudflared-system
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:2w5mpJv9CMrmV+xXF9fs3+9oxqhBHpSDTbOzhUcFQJz75nRWUkrCPWS5kKBSXuoS0V6Ezto0BaO6xSbcSXqmyx0DAcri4WHNcgceLfad5DY2wpl7uI6S9UwtqosNyOySg4xf4LAbKNZrVpTz2q58+qeKvCIjPJu5JPZbfP4Gc8kxud5Fyesoh4rJjG/4y9dary0SIVVF7FoOFvFHPXNBFEXiFrzP+aGovmauhXiKI3OhPFK4vHKgTqsSXLljMq9M1XTJMA2b+m+W9iwiZbb/lMi4bUxhKPDFbpw28/2h7HcJy8gsRUbKosqDMbK57mAwT31/IoDPGAU=,iv:+2gk84bG7OupdNMqFH3kzYyee1tL6K3L7YyWnT3fhFg=,tag:heBRYsiyRWEQNRELGlyd7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSDVxd0RTV2Q4UzRpZXZj
            NGs3MFZlcXUvZ1Arb1VxbjZrYmdsZ0R6NVc0Ck9CMUpDY1N1M3RpcjN0dEQ5aTE0
            YXdqbFRDYlFVNzFoSVZKUUFzT0lWTUUKLS0tIENVQ09ZOFNrWEFVUkpnaDllRkt3
            ZGJJbFg2NGpGMGd3eUhpK2dyN2lyOW8KLttKSFqxXy1KaZtnhTGqtC5I/olNRAs2
            ArqNHc1Gm81hS5/QfbBH+gW4f23ExDDJOb7s5m/IO8O2dYDDpVH/Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T18:59:48Z"
    mac: ENC[AES256_GCM,data:N6pTa18WNeLntnDdS5zeF0GV9DWo11gCSr/0Izn6Pu8CQex2GkERtTkVsOBMe3u9a9RwJHDJj4Jnwjly/hana8nLrSGZKXprRUxlHEHpyTBulmNU8qThTyxD5J1b22W5PyysPz/cBeTAgVSwvcVDKjnpUsTkTraHWzT7y7OCUfM=,iv:pU+aODUjdQR/Ftg4v1EwZWvIfMLpoH+V/jmcoDwVa4s=,tag:OSP9r47mbFiJAsr5+icjxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
