apiVersion: v1
kind: Secret
metadata:
    name: api-secret
    namespace: localizer
type: Opaque
stringData:
    CLERK_ISSUER: ENC[AES256_GCM,data:xbUYldtUkGzZO7THZ2P+Mksfke0acXA1GVmsgHjQAH4H9nDeAAFc8Z+z,iv:9QFzvKu1cSkSHAhGmrgrIqQWIuoOfmtgvlIsELB3ODY=,tag:nadX3M8Z1JEL6Pw7bldY4w==,type:str]
    API_ALLOWED_ORIGINS: ENC[AES256_GCM,data:iDPnB+YNPb0mGI0NcRgu1MrW1z21+9WdraEUX9LZek4/aR4+d8pWF3oGEFWfgl6XCKYg4fXqx7JfUUvWXYqyi+CeIw==,iv:9AJaYWQuHGjGp/4OEgaCPrkJ9KP+zlkYPMRQYdmiXHE=,tag:+/ITKTQS1RRdArchyfMJJg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Puc0uHopmu1XlHyFzfuXWoM3AZ6v,iv:6NVB+F7mW7SKhypHG9uNScw5mLCDEmeQY4+2lwz4BsU=,tag:D9aQLC55bFRtHrCTg4aVEQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:0RHrItNRjC2wf9mc0M4BzOM/oLpe,iv:yj0hQEG2zmrSy7krE/W+oswDWMQb4qR6G7k3YeeR0mc=,tag:KS7YsF7paYcmzN1RWCjnOw==,type:str]
    BREVO_API_KEY: ENC[AES256_GCM,data:wkVwXzoRJLCSIZOWK1UfWrwmaB2oRFO+nZdnnxRzMDMUDawEcUD4L86Y7PT/PNUkuJ2UX/a45GSX/GEJVR2I4QsV0xis2VZfDKNg9PQWdH+jki0J9IcLy5yV,iv:2TsKDPzDTAroxJohVYpzSQk+Qel2fJFI8vP7pYASVgI=,tag:FEBiehEi3FFWPBGgAGIjHA==,type:str]
    BREVO_ALERTS_FROM_EMAIL: ENC[AES256_GCM,data:No/1dM+puhFcYRT+lzw7zb8=,iv:PnBZRqRNOnRNTUa309rZKK8B/2UjC8gIuww/aXa8QCM=,tag:VzsOIs/sRdD0KS+CYwFV5A==,type:str]
    BREVO_ALERTS_FROM_NAME: ENC[AES256_GCM,data:QCfHMGFXFpip,iv:Q9vhNo029THlFurRaT9HqL4jhHd6+02J+K9jXiiZjYM=,tag:/wo5UbYb4cQoHcBmF0hVGQ==,type:str]
    BREVO_REPLY_TO_EMAIL: ENC[AES256_GCM,data:VuohWW35rcN2RZOw0tygBJk=,iv:1Y9RgtIw7+dGafI8Z+QXUE4VgtwRuLDuMzO8NxAoYgE=,tag:4iXuWyjptOhGD1ML884pEg==,type:str]
    BREVO_REPLY_TO_NAME: ENC[AES256_GCM,data:SZeBuNTYfneG,iv:wvmqQkGhdIg1Re/urnpMSfUh4YwfkdvrezQdKbSjdrM=,tag:qtLWe402sr19HzsC/p5i3Q==,type:str]
    FRONTEND_BASE_URL: ENC[AES256_GCM,data:SssUgBY8v6UcYytD2N2Gl54xs+ss44P2,iv:s08uE9SZl12DAQOuKbWNybfHUwCSI+kpRdIr3Gyk2ic=,tag:B2zFV+NlewuIOGh4QS867A==,type:str]
    CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:3FjjsiWAscQdxqQd6rzXQ5zyI9Zbur80jalrG0s2zwxeDveHksMu4sjrwIkVJ3l/LF8IeceG3f4YK3PmW8U6iw4HkY2AJihQIzoe/5FL4BiNqgGhyaw8Aq8K/7TF5PVJO+yuKfjLGqz9o/7WilkDsTrSnl+7AoE+ffEDjUzTieD+QHX6HSMSxvE+yxKcwiuuhNNxRaU/L7SGN5Gq7A74SCtFguVg9mUxPgzUO9NknTEBfuLuxXMhsA==,iv:H/FqHnJRbmp6BXQb9HTZI2Tb9DMYjMzv/dYWzv4t8CA=,tag:cdoU6HpdBlMJG2ukpfTCRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQTBUOVN3Q2NtekxHVzhB
            TVBIL2k1YzZEU3doOHFwaUxKQ0FXbWdld2k0CkU0WjBnTVl2NzVIai9PbVBGWTF5
            MTJ0cWlxWFJUcnYxL0VLTExJOUdWTGsKLS0tIDFVNTZHUFNPTUM0MVZyTlRUNm5j
            TkR4M2w2MEp4TVltNTE4MDc1YWtGbE0KAf1dbMWQbHqSXq0pAQui40g+GZgJ0S0o
            HEEmZSygKG8FLYlpkdTH+JIDGteU3T2uFgY1vFvUFNOBZ9tZCayjHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T20:42:18Z"
    mac: ENC[AES256_GCM,data:Ki+scI9FYOAv1BVfHC8bx0TPVuE5IUmf2J6q9VL9i4W9jdDvgAhABIVYZABkr7j2qGpUIf4PO3Oit+xKM2jOd0VXUCoiJk13s39AGg/nvPAu+EuvYFGaBFKX+cHYG5aOjqF42kvUtOqwmVlnrea6y5DYDvVshmPqg1rbSgdPY7I=,iv:8cUTwFMjBIYyxeNz/gCyMoqfriN5BQhoCvj127L0gZY=,tag:1qmRzBraQdWrX3Fl5ytr4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
