apiVersion: v1
kind: Secret
metadata:
    name: minio-root-credentials
    namespace: minio
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:YVENYB4=,iv:SUXQf/HkL6Fo+x1+9Kt1aAEYACL1jqLZghPIdLYFix4=,tag:mHzt+cHuC4pTv5qUSeKOfg==,type:str]
    rootPassword: ENC[AES256_GCM,data:twlJctiCRwRVZAehw74eGUJYMeeYuBTM,iv:bvkeDC/G0D0GKIeFYKCboylNETIUPJKAQrk6uKtV8vU=,tag:4UkVxw+DIB3LQQXSPf6m/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0LzlQMC91aVYvOEhSR2xq
            WFEvTFJhMGlIRWdHQXRsYk1NdFpuS3JsVmtRClpqcS9aMUxCbUM1Y2piVDhzUlE2
            TmZuaTZ4THl1bnFmZ2czeHB2aXRWSE0KLS0tIHd5QzdLTGtJNUVJUXZZNmFUUDBL
            V2pLV0gyYlkzdS95ZzZ3WElNSGFxVjQKpFnA3nC/8IDu3UpvGA1Qc7XXGhh6MWq5
            F9D01+on6rDk3GrBQ7NtcAsu7ib9tZTEvnbIazrL9xxN05GLtRghQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T20:09:21Z"
    mac: ENC[AES256_GCM,data:tI27xvhOlVapqurQ3T4ebDl/UJixG52DuMshHjDvLQcANKNAboMBWegSgicBiFuJk18VcQQxT9afahlkMw+WT8SHCYCA32vjpaiBRZznK3nYW5q4QlArwjVXUNaG+tXj3rSxP6sJbx3mQl052XFu+8FCudORgTyxVsFdN+KQ1lo=,iv:iu86lqzJYyFn8egDdmGabI1wtadMvvs1Z749XulRmLo=,tag:cPUVvIiq+poJn6mtMszsLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
