apiVersion: v1
kind: Secret
metadata:
    name: ai-agent-secret
    namespace: ai-agent
type: Opaque
stringData:
    #ENC[AES256_GCM,data:w8+cF/n8Dw==,iv:EJ+NkPOpMNHUP8Sc1kMnGLfFf/1excoWP3mIU5nfJ78=,tag:UIkxZWRhjI6SzZvu2ifrSw==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:rtywbgri,iv:RxLz1gMcLNdHl3ayI+ESmZy0uNHv1WfteWHTzfZHNfw=,tag:9s9BZnZylZaQkgM2B7zZPg==,type:str]
    OPENAI_API_URL: ENC[AES256_GCM,data:YWsnU+DjOoeM7W520nVgSX8g0+Cwv1u3Nn4lIHESJw==,iv:g9PLnkKz3J9T4HPitx+mFCZ4SwgdmU2k0/6iJb3ai0g=,tag:ArD9s+ucvFzIy2iMtmdQUw==,type:str]
    MODEL: ENC[AES256_GCM,data:lUJqXS2GIwYvUd8=,iv:ElLqKjyVJB9z8i6PVDhj90q2l1ZrgeSFz1aVqt8dTzI=,tag:9ANdh77NYHntK/Vv8wvRVQ==,type:str]
    #ENC[AES256_GCM,data:fRj6yCglLf7K,iv:0NVzTBrmxNF0Q5cJoPnQ9eybosOx7AXVCTJZQIunC0w=,tag:gKaClJxnouDFss182ZL0qw==,type:comment]
    TELEGRAM_ACCESS_TOKEN: ENC[AES256_GCM,data:ParHMJiBf+YQ/OzTt9S/tk26OPUayxnmfMtbPIvPOS/Ntfnd3UklOMfj4D4JMQ==,iv:Z3vdkBG/6Hl0LJNjn16Kdgm5lRqtBt7SXd40ayQCSzI=,tag:s03CJumgtOnM3aIihDvJqA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:wL0K0Jlb2Tz3+A==,iv:lPVLsnvRteqB7DUov6hA8niiXOFoRJ4TM09jgWHqHkI=,tag:oG1VkgPci8+lcDNQIyR9mg==,type:str]
    #ENC[AES256_GCM,data:rGNoPYTro3MG,iv:ptoI6zCixOWQGgEVnC9+AC18Z6PVhN2VHnKn9rYaYyA=,tag:HGKanMgNjnxVot2bLPxhKg==,type:comment]
    username: ENC[AES256_GCM,data:4ggUDVVZ7XM=,iv:vDFoFnjrVNtlLD6YbOu5dE4IR6I6c7jnsmQd5KAD/Is=,tag:67QohikiYCoeGUqXGA/HDw==,type:str]
    password: ENC[AES256_GCM,data:0luxTf9lY8YanVL8VGEG,iv:/J4I9shJWVr2j557bRDYSZEw3+adJKDoNEG+3CPk1/Y=,tag:8dpg9ck1ulZ78Nim9ijJIA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:3Bduwl5zuxnO+Jaw6BUKWVBTAkPlvvfPeruFMneivsBQd9/I0LBd0+M/RJjaiTzDKxDPZhqLqyUS+RGydrRI5LXFvqb08HZL+tL/GYp8CuYinXriCnr+xabSrC+fvTia3Lw=,iv:uRwba+9bI9hvXlG3LDVUTGadE+O2S4kceuw1pI39I5U=,tag:hR++4uIZ8HJw5g9nETBhzA==,type:str]
    #ENC[AES256_GCM,data:3IdpSeFVWO707dHH6l4O,iv:30zdaYD+c4pbf68xp5FJJCc16fBldP3izqL4VG8OUL0=,tag:UDvX+x3zljHJr42FkHHFbw==,type:comment]
    OPEN_WEARABLES_API_KEY: ENC[AES256_GCM,data:d/Zt6TwSppDD/8zz+FRWZP+HpsK/LU9Oc3yqXUOFG/R08Bo=,iv:p+ZOlhbze7M4fyma2jnEsSEpd76p7FLELgXAzYJG8dc=,tag:agOZAOxjQQoAGblmlb+8xg==,type:str]
    OPEN_WEARABLES_USER_ID: ENC[AES256_GCM,data:GZcWeEez8PDsJGQzYABBQm8frfWdwezMs7NUD+ENv+yqJ8sa,iv:ddYyd6IDHzf7pFbnu9+2YK0gjscrETQ3UrxPdEseOG4=,tag:Tv68cGkYOLAx7DFoL9saaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeCtNeEYvSjdMejIwRkRB
            d3ZqSUNDNlFnZU04a2xURC9jRC8vZjJORGp3CmtrN2NLTzhBS2NrYksrQUN0QVBZ
            eU5JaE5mQklkNTh3QXdtcGpYVlROdW8KLS0tIGpKalFtOUNMSHhsTW0wTGdCMnlF
            TDJjaWM4R2xDeXR3RGxtMUJwczRjeTQKI7YQ+q3SUiCVZjcKTbT+pPf/pM35asWy
            9Hy0nrO1xxRUQdac3J2OhHXe/0fVeW7K0ypSNZPKVvm+yB1SCld6Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T11:38:18Z"
    mac: ENC[AES256_GCM,data:u5mODVr27tLmFEukGFYVIet0a/NbjeS12WrN5Q2p3EU0hAVQTo1vPlbLsUHC/XImagSuCbCi2ZWJL8TKIi0jq5eIzCIU7H1x3FpCIU/0dIvdhEIDpm1xWFxT3nEqenrUVlKc11scqCb+tVZFjhIFULY16SoGI8EsWFbc9IhB6xQ=,iv:IsH9wkZexue1qMIL0x1O7a8HLLr+TifU0cQsZd0GeMQ=,tag:H/sjDuv1Fgb35AGrDDGODg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
