apiVersion: v1
kind: Secret
metadata:
    name: ai-agent-secret
    namespace: ai-agent
type: Opaque
stringData:
    #ENC[AES256_GCM,data:w8+cF/n8Dw==,iv:EJ+NkPOpMNHUP8Sc1kMnGLfFf/1excoWP3mIU5nfJ78=,tag:UIkxZWRhjI6SzZvu2ifrSw==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:rtywbgri,iv:RxLz1gMcLNdHl3ayI+ESmZy0uNHv1WfteWHTzfZHNfw=,tag:9s9BZnZylZaQkgM2B7zZPg==,type:str]
    OPENAI_API_URL: ENC[AES256_GCM,data:YWsnU+DjOoeM7W520nVgSX8g0+Cwv1u3Nn4lIHESJw==,iv:g9PLnkKz3J9T4HPitx+mFCZ4SwgdmU2k0/6iJb3ai0g=,tag:ArD9s+ucvFzIy2iMtmdQUw==,type:str]
    MODEL: ENC[AES256_GCM,data:lUJqXS2GIwYvUd8=,iv:ElLqKjyVJB9z8i6PVDhj90q2l1ZrgeSFz1aVqt8dTzI=,tag:9ANdh77NYHntK/Vv8wvRVQ==,type:str]
    #ENC[AES256_GCM,data:fRj6yCglLf7K,iv:0NVzTBrmxNF0Q5cJoPnQ9eybosOx7AXVCTJZQIunC0w=,tag:gKaClJxnouDFss182ZL0qw==,type:comment]
    TELEGRAM_ACCESS_TOKEN: ENC[AES256_GCM,data:ParHMJiBf+YQ/OzTt9S/tk26OPUayxnmfMtbPIvPOS/Ntfnd3UklOMfj4D4JMQ==,iv:Z3vdkBG/6Hl0LJNjn16Kdgm5lRqtBt7SXd40ayQCSzI=,tag:s03CJumgtOnM3aIihDvJqA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:No9GBZuJOXisCg==,iv:R5rKav7+rVbDY7L4Ag9Rnbq86Hscy8A892hg/2CIAHw=,tag:bN/Pu8dKit28kCD8CZ46pg==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeCtNeEYvSjdMejIwRkRB
            d3ZqSUNDNlFnZU04a2xURC9jRC8vZjJORGp3CmtrN2NLTzhBS2NrYksrQUN0QVBZ
            eU5JaE5mQklkNTh3QXdtcGpYVlROdW8KLS0tIGpKalFtOUNMSHhsTW0wTGdCMnlF
            TDJjaWM4R2xDeXR3RGxtMUJwczRjeTQKI7YQ+q3SUiCVZjcKTbT+pPf/pM35asWy
            9Hy0nrO1xxRUQdac3J2OhHXe/0fVeW7K0ypSNZPKVvm+yB1SCld6Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T17:36:17Z"
    mac: ENC[AES256_GCM,data:n7BcODqYr7BGj+XzIOtnsc4aKoSPUkVpnSw1agz0o1xpfN04dVgQxpbAw3iXNGQx/DKMiMfUnk/QL4dbyk3divuW5R89lAgaMBXw7frQy0ElXvaITRTBN5Z+KJZPlytBUyJ+c3///QCWZxKJLc0sW+IdVYcU9Y5MG0Le3Qqy1tw=,iv:KYECh06nIlflulo1+VS4IufV8/r2YSXuc8ZoOHVTwlo=,tag:aJJ1SOpQ5Zz23X7oS5z5Iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
