apiVersion: v1
kind: Secret
metadata:
    name: ai-agent-secret
    namespace: ai-agent
type: Opaque
stringData:
    #ENC[AES256_GCM,data:w8+cF/n8Dw==,iv:EJ+NkPOpMNHUP8Sc1kMnGLfFf/1excoWP3mIU5nfJ78=,tag:UIkxZWRhjI6SzZvu2ifrSw==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:rtywbgri,iv:RxLz1gMcLNdHl3ayI+ESmZy0uNHv1WfteWHTzfZHNfw=,tag:9s9BZnZylZaQkgM2B7zZPg==,type:str]
    OPENAI_API_URL: ENC[AES256_GCM,data:YWsnU+DjOoeM7W520nVgSX8g0+Cwv1u3Nn4lIHESJw==,iv:g9PLnkKz3J9T4HPitx+mFCZ4SwgdmU2k0/6iJb3ai0g=,tag:ArD9s+ucvFzIy2iMtmdQUw==,type:str]
    MODEL: ENC[AES256_GCM,data:lUJqXS2GIwYvUd8=,iv:ElLqKjyVJB9z8i6PVDhj90q2l1ZrgeSFz1aVqt8dTzI=,tag:9ANdh77NYHntK/Vv8wvRVQ==,type:str]
    #ENC[AES256_GCM,data:fRj6yCglLf7K,iv:0NVzTBrmxNF0Q5cJoPnQ9eybosOx7AXVCTJZQIunC0w=,tag:gKaClJxnouDFss182ZL0qw==,type:comment]
    TELEGRAM_ACCESS_TOKEN: ENC[AES256_GCM,data:ParHMJiBf+YQ/OzTt9S/tk26OPUayxnmfMtbPIvPOS/Ntfnd3UklOMfj4D4JMQ==,iv:Z3vdkBG/6Hl0LJNjn16Kdgm5lRqtBt7SXd40ayQCSzI=,tag:s03CJumgtOnM3aIihDvJqA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:wL0K0Jlb2Tz3+A==,iv:lPVLsnvRteqB7DUov6hA8niiXOFoRJ4TM09jgWHqHkI=,tag:oG1VkgPci8+lcDNQIyR9mg==,type:str]
    #ENC[AES256_GCM,data:rGNoPYTro3MG,iv:ptoI6zCixOWQGgEVnC9+AC18Z6PVhN2VHnKn9rYaYyA=,tag:HGKanMgNjnxVot2bLPxhKg==,type:comment]
    username: ENC[AES256_GCM,data:4ggUDVVZ7XM=,iv:vDFoFnjrVNtlLD6YbOu5dE4IR6I6c7jnsmQd5KAD/Is=,tag:67QohikiYCoeGUqXGA/HDw==,type:str]
    password: ENC[AES256_GCM,data:0luxTf9lY8YanVL8VGEG,iv:/J4I9shJWVr2j557bRDYSZEw3+adJKDoNEG+3CPk1/Y=,tag:8dpg9ck1ulZ78Nim9ijJIA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:3Bduwl5zuxnO+Jaw6BUKWVBTAkPlvvfPeruFMneivsBQd9/I0LBd0+M/RJjaiTzDKxDPZhqLqyUS+RGydrRI5LXFvqb08HZL+tL/GYp8CuYinXriCnr+xabSrC+fvTia3Lw=,iv:uRwba+9bI9hvXlG3LDVUTGadE+O2S4kceuw1pI39I5U=,tag:hR++4uIZ8HJw5g9nETBhzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeCtNeEYvSjdMejIwRkRB
            d3ZqSUNDNlFnZU04a2xURC9jRC8vZjJORGp3CmtrN2NLTzhBS2NrYksrQUN0QVBZ
            eU5JaE5mQklkNTh3QXdtcGpYVlROdW8KLS0tIGpKalFtOUNMSHhsTW0wTGdCMnlF
            TDJjaWM4R2xDeXR3RGxtMUJwczRjeTQKI7YQ+q3SUiCVZjcKTbT+pPf/pM35asWy
            9Hy0nrO1xxRUQdac3J2OhHXe/0fVeW7K0ypSNZPKVvm+yB1SCld6Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T19:51:29Z"
    mac: ENC[AES256_GCM,data:AFI2ONceO/okVUFVhiZYbcQNx6qUOkXW625aoSnJ68Sx0VXYq75QiamD+SW0Fqcj+vgSdyYBn1lHOgxWkNVCMQcJIkrqXfGqj5069uXeCjvzX53i5rmIV93lZuqaJTuB8U+EBNoMPHsPJKiJt3NH3+8CPGSEmNUgIRpUuMMfsZ8=,iv:GQm2qYsFr0yeBaDwZ7hZEukqiycDmNNJJxRtwMoiw0k=,tag:zfIWyBTuJ1C8QCZUNzRbsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
