apiVersion: v1
kind: Secret
metadata:
    name: agent-secret
    namespace: ai-agent
type: Opaque
stringData:
    TELEGRAM_ACCESS_TOKEN: ENC[AES256_GCM,data:RJaGP5mAZV8UoHasKg/zwHTJWfCW87GT804O7Ovb5LpSAQkjhJwkJ6VFcRgOHA==,iv:trpebNH7Tzx9XKZ9u+j58gM2uhsxCUz6YzrOZvxkfgw=,tag:tmHdk7+tji8dd4Pytxxh1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaU1NODlUanhoTmJmTVhQ
            b1V1RVJuTEJvUXVxaU9QT3d0eExKRnFKa21jCnNuWU9hWEZtYXR6YkxCSzJnc25J
            eGwySVZ4UWlRbngxYTVrL3hlZ1hzTDAKLS0tIFdpQVllU21sNW5id0phTkNzNlFy
            SU5SRTdEeEhPbUFsQk9HNXMwbkVWWVkKKTDAgxMJz+/VzHQJFFfTk0cS8R8tCm7q
            zwx3OC8IjrvClFBB2Itmru5pMvrc1BP0woVyP/hHOw2hybz2bPi4gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T17:07:38Z"
    mac: ENC[AES256_GCM,data:iTmtUAJAW5yDgJl8YQwJRhc3/+U/gIjHCOjLpg5n18MlvkFdQ3n/9H1NP3KljFGpr1xcqH93zl6XV5y8DYTsNh/3ETmgS1hQbPjQlDoYiFguV1B3oU4fXJMfKsTCyT/mIyp+ckpd+Ll8jJSmW2YnWOYe3SzZLHRWLoP0kpXzuI0=,iv:dXHRiXqSJoZKt5RMpVXDocEk3jVU6FE6GzwCGMJYs34=,tag:XeNKmQz4tP3UAfP+3ssy+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
