apiVersion: v1
kind: Secret
metadata:
    name: telegram-bot-secret
    namespace: ai-agent
type: Opaque
stringData:
    TELEGRAM_ACCESS_TOKEN: ENC[AES256_GCM,data:RJaGP5mAZV8UoHasKg/zwHTJWfCW87GT804O7Ovb5LpSAQkjhJwkJ6VFcRgOHA==,iv:trpebNH7Tzx9XKZ9u+j58gM2uhsxCUz6YzrOZvxkfgw=,tag:tmHdk7+tji8dd4Pytxxh1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mth59q66qy6rz92u4x4jfhngrq0m8t4sy9xtmrhjs3c8c3n2p3ws93qfq0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaU1NODlUanhoTmJmTVhQ
            b1V1RVJuTEJvUXVxaU9QT3d0eExKRnFKa21jCnNuWU9hWEZtYXR6YkxCSzJnc25J
            eGwySVZ4UWlRbngxYTVrL3hlZ1hzTDAKLS0tIFdpQVllU21sNW5id0phTkNzNlFy
            SU5SRTdEeEhPbUFsQk9HNXMwbkVWWVkKKTDAgxMJz+/VzHQJFFfTk0cS8R8tCm7q
            zwx3OC8IjrvClFBB2Itmru5pMvrc1BP0woVyP/hHOw2hybz2bPi4gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T17:08:54Z"
    mac: ENC[AES256_GCM,data:bQpHay5u/3F0gn3+ncC8YqOJIsch9Q8IjAHPLQQtqD0zpezFB/Lf3XrYnRbkpNprH9vJBQTE/mIGVVYklcPFME+hRrQW3P1iDRDiyihsO47c/sELLQyZMpGtZxnREBdICT0/hlW+bFjVjAOIuCBM5sIkB+EvR9raVoNlP5af0aU=,iv:/CuPdf2yM8j7d/euZkoBgUkZzJIfq5WNzitT8J2PJ1A=,tag:MQxt+i3Qc5ivYMQAfpi6ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
